### ISSUE TITLE
[BUG] Table CE - 'Responsive table' style does not work

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#28]
**Describe the bug**
Table style 'Responsive table' (Appearance tab) is not applicable.
Page: https://demo.t3kit.com/content/static-content/table 

In the TYPO3 BE Table style 'Responsive table' at the Appearance tab was added to all Table content elements on the page. 

**Expected behavior**
If Table style 'Responsive table' is used tables should be fitted by the device viewport and be scrollable (horizontal scroll) 

**Screenshots**
![Screenshot_4](https://user-images.githubusercontent.com/26138552/95591951-a5c8e500-0a50-11eb-9ee2-7c4ae5695724.png)

**Smartphone (please complete the following information):**

- Device: not specific. The bug is present on all mobile devices (Example, iPhone 11) 
- OS: not specific 
- Browser - not specific 

**Additional context**
The bug could be present because of style was added to the incorrect class

**Comment by dmh** [comment]
https://github.com/t3kit/t3kit/commit/21129c3203ed263f6e624dd47a27c2995fc6d8c9
