### ISSUE TITLE
[BUG] Header CE - Long words are stretching the screen view on devices 

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#31]
**Describe the bug**
Long words go out the screen edge. Especially related to the different languages (SE, FI, NO, DK, DE) 

**Conditions:** Header content element. Heading style - Large heading style. 

**Expected behavior**
Long words should be moved to the new row (via soft-hyphen or another solution) or scale down them.

**Screenshots**
![Screenshot_8](https://user-images.githubusercontent.com/26138552/97180050-3ff39180-17a2-11eb-8296-cc66804f86d9.png)

**Smartphone (please complete the following information):**

- **Device**: tablets (portrait view) and mobile devices
- OS: all
- Browser: all

**Additional context**
The  bug was found on the current Aimpoint project 
![Screenshot_8](https://user-images.githubusercontent.com/26138552/97180161-61ed1400-17a2-11eb-8bdc-5f76ee3bf9f7.png)

On the installation is implemented soft-hyphen for CKE. But looks like it's not used for Header CE.

**Comment by dmh** [comment]
Soft Hyphen is the solution
