### ISSUE TITLE
[BUG] Main menu (drop-down list) and hamburger menu are not properly working on mac OS/ iOS

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#33]
**Describe the bug**
No possibility to open the drop-down menu at the main navigation menu. 
No possibility to open the hamburger menu on devices. 

**Expected behavior**
Menu one of the major functionality. So it should open to see the drop-down menu and menu sub levels.

**Screenshots**
![Screenshot_9](https://user-images.githubusercontent.com/26138552/99657591-06dbd380-2a67-11eb-984a-17eb6bc8b40f.png)

**Desktop:**
- OS: macOS (was tested on Catalina) 
- Browser:  Safari
- Version: 13.1

**Smartphone:**
- Device: no specific 
- OS: iOS13
- Browser: Safari and Chrome 

**Additional context**
On the latest versions of mac OS (Big Sur) and iOS v.14 menu works well.

**Comment by OlenaBulat** [comment]
@mesosa ping

**Comment by dmh** [comment]
@OlenaBulat currently we are not supporting  Safari13 and ios13
