### ISSUE TITLE
[TASK] execute composer test inside PHP container ???

### ISSUE THREAD

**Issue by dmh** [t3kit/t3kit-starter#37]
execute composer test inside PHP container

**Comment by mabolek** [comment]
I tried out a solution for DDEV.

This works in most cases:
`ddev composer test`

However, if XDebug is enabled, it's better to disable it:
`ddev exec "XDEBUG_MODE=off composer test"`

I guess the same approach for Docker too.

Here's a bash script to continue from:

```
if [ -n "$(command -v ddev)" ] && [ -f ".ddev/config.yaml" ]; then
    ddev exec "XDEBUG_MODE=off composer test"
else
    XDEBUG_MODE=off composer test
fi
```

**Comment by mabolek** [comment]
The above can be implemented in composer.json like this, but it requires that git runs it in a bash-compatible shell.

```
  "extra": {
    "hooks": {
      "pre-commit": [
        "if [ -n \"$(command -v ddev)\" ] && [ -f \".ddev/config.yaml\" ]; then",
        "    ddev exec \"XDEBUG_MODE=off composer test\"",
        "else",
        "    XDEBUG_MODE=off composer test",
        "fi"
      ]
    }
  }
```

**Comment by dmh** [comment]
@mabolek 
Thanks for the hint, let's keep it here in case that it will be needed in the future. For now, I don't see a reason t to merge it because of two points:
1. This does not solve the main issue of creating an independent containerized environment for tests, and I am not sure yet that we really need this, I am going to wait and collect more feedback.
2. For me `XDEBUG_MODE` solution sounds like a very local issue and I want to wait for more feedback to understand is it a real common problem

I will add it to the **t3kit 10.1.0** plan

**Comment by mabolek** [comment]
Hi @dmh!

> This does not solve the main issue of creating an independent containerized environment for tests, and I am not sure yet that we really need this, I am going to wait and collect more feedback.

I would consider an _independent_ environment as a good step two.

The foremost issue this is solving from my perspective (i.e. running an older PHP version on my computer than on the site) is to run the tests in the correct PHP version.

> For me XDEBUG_MODE solution sounds like a very local issue and I want to wait for more feedback to understand is it a real common problem

This issue will be valid for anyone running composer when XDebug is enabled in PHP. That combination is probably fairly common.

Granted, "everything" you need to do is disable XDebug before you run composer and then re-enable it, but that's rather inconvenient compared to adding `XDEBUG_MODE=off` to the script.
