### ISSUE TITLE
[Task] Update documentation for sed commande line on Linux

### ISSUE THREAD

**Issue by joniroutypo3** [t3kit/t3kit-starter#39]
**Describe the task**
The documentation line for "Rename newcustomproject to your projectname" on https://github.com/t3kit/t3kit-starter#quick-start is ok for sed on Mac but not on Centos (and maybe for other linux)

On mac the line is OK.
For Linux we need to remove the '' juste after "| xargs sed -i"

grep -rl 'newcustomproject' public/typo3conf/ext/theme_projectname | xargs sed -i 's/newcustomproject/projectname/g'

Jonathan

**Comment by dmh** [comment]
ec5399107efde5300a85babb0878af361e7a4f4b
