### ISSUE TITLE
[BUG] News record - Invalid value for Column field

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#46]
**Describe the bug**
when new content element was addedto the News record in the Content element -> Column present invalid value [ INVALID VALUE ("0") ]

**To Reproduce
Steps to reproduce the behavior:**

1. go to the News folder in TYPO3 BE
2. go to the News section 
3. add new News record 
4. go to the Content elements tab
5. add new Content element 
6. See error at **Column** [ INVALID VALUE ("0") ]

**Expected behavior**
To Column field was added/rendered the correct value.

**Screenshots**
![Screenshot_43](https://user-images.githubusercontent.com/26138552/111653993-02ef7080-8811-11eb-9c2f-d9cbe78bde61.png)

**Comment by dmh** [comment]
we are not fully support news for now
