### ISSUE TITLE
[FEATURE] Low sidebar navigation experience (UX/UI)

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#47]
**Is your feature request related to a problem? Please describe.**
It's not clear for users that there are 2nd and 3rd menu levels. 

**Describe the solution you'd like**
From my perspective 
1. would be great and more clear for users to have the option to display arrows; 
2. add more margins/paddings for 2nd/3rd/4th/etc. levels to have them more visible;

**Additional context**
![Screenshot_32](https://user-images.githubusercontent.com/26138552/111832917-10ccf080-88fa-11eb-837e-36eab076f5fb.png)
![Screenshot_33](https://user-images.githubusercontent.com/26138552/111832921-11658700-88fa-11eb-9f82-71d5c718754d.png)
![Screenshot_34](https://user-images.githubusercontent.com/26138552/111832922-11658700-88fa-11eb-8c79-1a42efcc25d9.png)

**Comment by dmh** [comment]
the idea to keep it as simple as possible, with the possibility to easy-adjust
