### ISSUE TITLE
[BUG]  Bullet/Numbered list - Center/Right alignment 

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#49]
**Describe the bug**
1. Bullets and text are misaligned when choose to align by center/right. 
2. Bullet list CE has no settings to be aligned by center/right. 

**To Reproduce**
1. In the typo3 BE go to page
2. add news content element Regular Text Element
3. in the Text field add the list and insert Bullet list/Numbered style
4. add Align Center or Align Right 
5. Save your changes and View the page on FE
6. See issue - Bullets/ numbers and text have different alignment. Bullets/ numbers are always placed on the left. 

**Expected behavior**
Could be few variations on how to implement it:
1. For Bullet list CE - implement alignments as on reference image (**_Expected result 1/ 2_**). When bullet list had the possibility to have the alignment right/center/left and both text and bullets are aligned by the same vertical line (and if there is multiline text it should be aligned with the text);
2. For the Bullet list in CKE (RTE) - bullets appear next to the text. So here the main is text and bullets just follows the position;
3. For both options implement option both text and bullets are aligned by the same vertical line.

**Screenshots**
![Screenshot_12](https://user-images.githubusercontent.com/26138552/112507468-545ea900-8d97-11eb-8e32-df79da303037.png)
![Screenshot_13](https://user-images.githubusercontent.com/26138552/112507470-54f73f80-8d97-11eb-8c39-947065b52309.png)
![Screenshot_14](https://user-images.githubusercontent.com/26138552/112507471-558fd600-8d97-11eb-8f7b-94695d987ac0.png)

**Desktop:**
no specific

**Comment by mesosa** [comment]
@dmh maybe use 'list-style-position: inside;' for the li styling?
