### ISSUE TITLE
[BUG] Different opacity at dividers 

### ISSUE THREAD

**Issue by OlenaBulat** [t3kit/t3kit-starter#50]
**Describe the bug**
Divider CE and divider in the Text CKE have different opacity. 

**Expected behavior**
Dividers should look the same. The main reason is when using both dividers on the same page it's visible that they are a bit different. 

**Screenshots**
![Screenshot_15](https://user-images.githubusercontent.com/26138552/112844978-fdb1e180-90ac-11eb-8ec4-7a7d6eb51d6d.png)

**Desktop/ Device:**
no specific

**Additional context**
Divider CE - `opacity: .4`
Divider in CKE - `opacity: .25`

**Comment by dmh** [comment]
I guess there is should be a reason for that :)
