### ISSUE TITLE
[BUG] Browser shows unstyled content for a brief moment during refresh

### ISSUE THREAD

**Issue by pxamike** [t3kit/t3kit-starter#54]
**Describe the bug**
When user hard-refresh the page, a non styled website appears for a moment.
Has started to occur during t3kit 10 beta, at least it didn't happen in the t3kit 10 alpha-based project I was involved in.

**To Reproduce**

1. Go to, https://demo.t3kit.com/content/menu/abstracts
2. Refresh like a maniac! :-D

**Expected behavior**
No blue links etc.

**Video**
https://user-images.githubusercontent.com/12510409/116700543-2fc5a480-a9c7-11eb-965c-d885c67f5bb2.mp4

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome, Firefox
- Version 90, 88

**Comment by dmh** [comment]
should be fixed now
