### ISSUE TITLE
[BUG] Site Footer links don't use the target-value of the links

### ISSUE THREAD

**Issue by pxamike** [t3kit/t3kit-starter#57]
**Describe the bug**
- A page of type "External link to url" is created. The url field is "//www.facebook.com/" and Target is "_blank".
- A Site Footer-element is created and in the Links column 1-field, this page is included.
- However, in the front-end, the link in the links-column of the Site Footer-element does not have any target, so it will always be opened in the same tab or window.

**To Reproduce**
See above.

**Expected behavior**
If a target is defined on a page that is included in the Links columns of the Site Footer-element, it should be used.

**Comment by dmh** [comment]
already fixed
